### ISSUE TITLE
Reorganize unittests for `tc_surge_geoclaw`

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_petals#148]
With #109  came a bunch of new unittests. One of them, `climada_petals.hazard.tc_surge_geoclaw.test.test_tc_surge_geoclaw.TestHazardInit.test_init`, takes 46 seconds on Jenkins (and, depending on the settings, up to 130 seconds on the Euler cluster).
According to our guide lines this is too much for any test let alone a unit test.

I suggest to

1. immediate measure: move it to the integration test
2. in the long run: rewrite the test so that it is done within reasonable time (<10sec)

**Comment by emanuel-schmid** [comment]
🙌 awesome! Do you also know how this can be sped up?

**Comment by chahank** [comment]
I will definitely try to find a solution :D

**Comment by NicolasColombi** [comment]
On my laptop it takes 18s 🙄

Other issue: there is an integration test failing on my machine, cell 3 of the tutorial ``climada_hazard_TCSurgeGeoClaw.ipynb`` fails as well, with the same RunTimeError of the test. Does the following test pass on your computer ? 
``climada_petals.test.test_tc_surge_geoclaw.TestGeoclawRun.test_surge_from_track ``

The error is the same for both the test and the tutorial:

The warning preceding the error:
``/Users/ncolombi/miniforge3/envs/climada_dev/lib/python3.9/site-packages/shapely/constructive.py:181: RuntimeWarning: invalid value encountered in buffer
  return lib.buffer(``
The error:
``RuntimeError: GeoClaw run failed``

**Comment by chahank** [comment]
Ok, so the unit test can be made very quick by making the centroids smaller. Fix propose in PR: #149

**Comment by emanuel-schmid** [comment]
On Euler the said test fails in yet another way:
```
[...]
2024-11-22 16:37:08,323 - climada_petals.hazard.tc_surge_geoclaw.geoclaw_runner - INFO - Output of 'make .output' in GeoClaw work directory:
/cluster/work/sis/cdss/schmide/climada/data/geoclaw/src/clawpack/clawutil/src/Makefile.common:111: *** recipe commences before first target.  Stop.

E
======================================================================
ERROR: test_surge_from_track (climada_petals.test.test_tc_surge_geoclaw.TestGeoclawRun.test_surge_from_track)
Test _geoclaw_surge_from_track function (~30 seconds on a notebook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cluster/project/sis/cdss/schmide/climada_petals/climada_petals/test/test_tc_surge_geoclaw.py", line 98, in test_surge_from_track
    intensity, gauge_data = _geoclaw_surge_from_track(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/sis/cdss/schmide/climada_petals/climada_petals/hazard/tc_surge_geoclaw/tc_surge_geoclaw.py", line 595, in _geoclaw_surge_from_track
    runner.run()
  File "/cluster/project/sis/cdss/schmide/climada_petals/climada_petals/hazard/tc_surge_geoclaw/geoclaw_runner.py", line 215, in run
    self._run_subprocess()
  File "/cluster/project/sis/cdss/schmide/climada_petals/climada_petals/hazard/tc_surge_geoclaw/geoclaw_runner.py", line 270, in _run_subprocess
    raise RuntimeError("GeoClaw run failed (see output above).")
RuntimeError: GeoClaw run failed (see output above).

----------------------------------------------------------------------
Ran 1 test in 40.183s
```

**Comment by emanuel-schmid** [comment]
This Geoclaw thingy seems to be somewhat experimental...

**Comment by chahank** [comment]
The package has not been deleted. I am not sure what you are missing.

**Comment by saeedsvz** [comment]
Hi @chahank, I am looking for this "climada_petals.hazard.tc_surge_geoclaw" and I cannot find it under climate_petals.

**Comment by chahank** [comment]
It is here: https://github.com/CLIMADA-project/climada_petals/tree/develop/climada_petals/hazard

**Comment by saeedsvz** [comment]
I got it, thank you so much for your help.

**Comment by saeedsvz** [comment]
Has anyone got this problem?

```
File ~\AppData\Local\miniforge3\envs\climada_env\Lib\site-packages\climada\util\config.py:54, in Config.__getattribute__(self, _Config__name)
     49 except AttributeError:
     50     conf_files = [Path(_find_in_parents(conf_dir, CONFIG_NAME))
     51                   if _find_in_parents(conf_dir, CONFIG_NAME)
     52                   else conf_dir / CONFIG_NAME
     53                   for conf_dir in CONFIG_DIRS[::-1]]
---> 54     raise AttributeError(  # pylint: disable=raise-missing-from
     55         f"there is no '{__name}' configured for '{super().__getattribute__('_name')}'."
     56         f" check your config files: {conf_files}"
     57     )

AttributeError: there is no 'tc_surge_geoclaw' configured for 'hazard'.
```

Seems like the "climada.conf" does not have the "tc_surge_geoclaw" in its attributes. Am I using the old version? I got this error when i wanna import the other modules from "climada_petals.hazard.tc_surge_geoclaw". Is there any solution to it? Thank you.

**Comment by peanutfun** [comment]
just FYI: The GeoClaw runner will run the GeoClaw executable in a subprocess, and will first try to compile it from Fortran if it does not exist (hence the Makefile execution). Compiling is a highly system-dependent operation, so it's not surprising that this fails in different ways on various systems.

**Comment by peanutfun** [comment]
I updated ClawPack in #193 and the tests run fine on the GitHub CI. Will close this for now.
